# Generated by Django 2.1.1 on 2018-09-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Date Changed')),
                ('fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('email', models.CharField(max_length=300, verbose_name='Email ID')),
            ],
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('sex', models.CharField(max_length=5, verbose_name='Sex')),
                ('id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbdata.Table1')),
            ],
        ),
    ]
