# Generated by Django 2.1.1 on 2018-09-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1',
            old_name='date',
            new_name='c_date',
        ),
    ]
