# Generated by Django 2.1.1 on 2018-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbdata', '0006_auto_20180922_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table1',
            name='fname',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
    ]
